knp_paginator:
    page_range: 5          # Número de páginas que se mostrarán en la barra de paginación
    default_options:
        sort_field_name: sort
        sort_direction_name: direction
        page_name: page     # Parámetro de URL que define la página actual
        distinct: true      # Filtra duplicados
